name: Build Black Hole

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Bootstrap vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg C:\vcpkg
        C:\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies
      run: |
        C:\vcpkg\vcpkg.exe install glfw3 glew glm

    - name: Configure
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: black_hole_windows
        path: build/**
